package com.asotec.riesgos.entity;
// Generated 16/07/2017 20:50:13 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlTransient;

/**
 * SgfSocio generated by hbm2java
 */
@Entity
@Table(name = "sgf_socio",
        schema = "public" //postgres
//schema = "dbo", catalog = "coop" //sqlserver
)
public class SgfSocio implements java.io.Serializable {


    private long codSocio;
    private Character codTipoSocio;
    private Date fecIngreso;
    private Character codTipoPersona;
    private Character codTipoId;
    private String numId;
    private Integer codParroquia;
    private Short codCanton;
    private Short codProvincia;
    private Short codBarrio;
    private Short codPais;
    private String nomSocio;
    private String apeSocio;
    private Short codActEconomica;
    private Short codInstruccion;
    private String nomJuridico;
    private Character stsSexo;
    private Date fecNacimiento;
    private Character stsCivil;
    private Character stsSocio;
//    private String nomRepresentanteLegal;
//    private String apeRepresentanteLegal;
//    private Character codTipoIdRepLegal;
//    private String numIdRelLegal;
//    private String nomConyuge;
//    private String apeConyuge;
//    private Date fecNacCon;
//    private Character codTipoIdCon;
//    private String numIdCon;
    private String dirDom;
    private String dir2Dom;
    private String telDom;
    private String telTrabajo;
    private String telCelular;
//    private Character stsOperadorCel;
    private String dirCorreo;
//    private byte[] imgFoto;
//    private String txtLink;
    private Date fecUsrmod;
//    private Long codUsrmod;
//    private String nomBeneficiario;
//    private String apeBeneficiario;
//    private Character codTipoIdBen;
//    private String numIdBen;
    private String dirTrabajo;
//    private String dir2Trabajo;
//    private String codTipoSangre;
    private BigDecimal valIngresoMensual;
//    private Date fecSolicitud;
//    private Character codOrigenIngresos;
    private BigDecimal valActivo;
    private BigDecimal valPasivo;
    private BigDecimal valPatrimonio;
    private BigDecimal valGastosMensuales;
//    private String codCausalVinculacion;
//    private Date fecCausal;
//    private Character codTipoVivienda;
//    private BigDecimal valVivienda;
//    private Short numTiempoTrabajo;
//    private Byte numCargasFamiliares;
    private Long codSocioConyuge;
//    private Long codSocioVinculado;
//    private Byte codRelacion;
//    private String txtObservacionRelacion;
//    private Byte codOficina;
    private String txtLugarTrabajo;
//    private Character codNivelEstudios;
//    private Character stsActualizaWeb;
    
    private long codCantonNac;

    public SgfSocio() {
    }

    public SgfSocio(long codSocio) {
        this.codSocio = codSocio;
    }



//    public SgfSocio(long codSocio, Character codTipoSocio, Date fecIngreso, Character codTipoPersona, Character codTipoId, String numId, Integer codParroquia, Short codCanton, Short codProvincia, Short codBarrio, Short codPais, String nomSocio, String apeSocio, Short codActEconomica, Short codInstruccion, String nomJuridico, Character stsSexo, Date fecNacimiento, Character stsCivil, Character stsSocio, String nomRepresentanteLegal, String apeRepresentanteLegal, Character codTipoIdRepLegal, String numIdRelLegal, String nomConyuge, String apeConyuge, Date fecNacCon, Character codTipoIdCon, String numIdCon, String dirDom, String dir2Dom, String telDom, String telTrabajo, String telCelular, Character stsOperadorCel, String dirCorreo, byte[] imgFoto, String txtLink, Date fecUsrmod, Long codUsrmod, String nomBeneficiario, String apeBeneficiario, Character codTipoIdBen, String numIdBen, String dirTrabajo, String dir2Trabajo, String codTipoSangre, BigDecimal valIngresoMensual, Date fecSolicitud, Character codOrigenIngresos, BigDecimal valActivo, BigDecimal valPasivo, BigDecimal valPatrimonio, BigDecimal valGastosMensuales, String codCausalVinculacion, Date fecCausal, Character codTipoVivienda, BigDecimal valVivienda, Short numTiempoTrabajo, Byte numCargasFamiliares, Long codSocioConyuge, Long codSocioVinculado, Byte codRelacion, String txtObservacionRelacion, Byte codOficina, String txtLugarTrabajo, Character codNivelEstudios, Character stsActualizaWeb) {
//        this.codSocio = codSocio;
//        this.codTipoSocio = codTipoSocio;
//        this.fecIngreso = fecIngreso;
//        this.codTipoPersona = codTipoPersona;
//        this.codTipoId = codTipoId;
//        this.numId = numId;
//        this.codParroquia = codParroquia;
//        this.codCanton = codCanton;
//        this.codProvincia = codProvincia;
//        this.codBarrio = codBarrio;
//        this.codPais = codPais;
//        this.nomSocio = nomSocio;
//        this.apeSocio = apeSocio;
//        this.codActEconomica = codActEconomica;
//        this.codInstruccion = codInstruccion;
//        this.nomJuridico = nomJuridico;
//        this.stsSexo = stsSexo;
//        this.fecNacimiento = fecNacimiento;
//        this.stsCivil = stsCivil;
//        this.stsSocio = stsSocio;
//        this.nomRepresentanteLegal = nomRepresentanteLegal;
//        this.apeRepresentanteLegal = apeRepresentanteLegal;
//        this.codTipoIdRepLegal = codTipoIdRepLegal;
//        this.numIdRelLegal = numIdRelLegal;
//        this.nomConyuge = nomConyuge;
//        this.apeConyuge = apeConyuge;
//        this.fecNacCon = fecNacCon;
//        this.codTipoIdCon = codTipoIdCon;
//        this.numIdCon = numIdCon;
//        this.dirDom = dirDom;
//        this.dir2Dom = dir2Dom;
//        this.telDom = telDom;
//        this.telTrabajo = telTrabajo;
//        this.telCelular = telCelular;
//        this.stsOperadorCel = stsOperadorCel;
//        this.dirCorreo = dirCorreo;
//        this.imgFoto = imgFoto;
//        this.txtLink = txtLink;
//        this.fecUsrmod = fecUsrmod;
//        this.codUsrmod = codUsrmod;
//        this.nomBeneficiario = nomBeneficiario;
//        this.apeBeneficiario = apeBeneficiario;
//        this.codTipoIdBen = codTipoIdBen;
//        this.numIdBen = numIdBen;
//        this.dirTrabajo = dirTrabajo;
//        this.dir2Trabajo = dir2Trabajo;
//        this.codTipoSangre = codTipoSangre;
//        this.valIngresoMensual = valIngresoMensual;
//        this.fecSolicitud = fecSolicitud;
//        this.codOrigenIngresos = codOrigenIngresos;
//        this.valActivo = valActivo;
//        this.valPasivo = valPasivo;
//        this.valPatrimonio = valPatrimonio;
//        this.valGastosMensuales = valGastosMensuales;
//        this.codCausalVinculacion = codCausalVinculacion;
//        this.fecCausal = fecCausal;
//        this.codTipoVivienda = codTipoVivienda;
//        this.valVivienda = valVivienda;
//        this.numTiempoTrabajo = numTiempoTrabajo;
//        this.numCargasFamiliares = numCargasFamiliares;
//        this.codSocioConyuge = codSocioConyuge;
//        this.codSocioVinculado = codSocioVinculado;
//        this.codRelacion = codRelacion;
//        this.txtObservacionRelacion = txtObservacionRelacion;
//        this.codOficina = codOficina;
//        this.txtLugarTrabajo = txtLugarTrabajo;
//        this.codNivelEstudios = codNivelEstudios;
//        this.stsActualizaWeb = stsActualizaWeb;
//    }

    public SgfSocio(long codSocio, Character codTipoSocio, Date fecIngreso, Character codTipoPersona, Character codTipoId, String numId, Integer codParroquia, Short codCanton, Short codProvincia, Short codBarrio, Short codPais, String nomSocio, String apeSocio, Short codActEconomica, Short codInstruccion, String nomJuridico, Character stsSexo, Date fecNacimiento, Character stsCivil, Character stsSocio) {
        this.codSocio = codSocio;
        this.codTipoSocio = codTipoSocio;
        this.fecIngreso = fecIngreso;
        this.codTipoPersona = codTipoPersona;
        this.codTipoId = codTipoId;
        this.numId = numId;
        this.codParroquia = codParroquia;
        this.codCanton = codCanton;
        this.codProvincia = codProvincia;
        this.codBarrio = codBarrio;
        this.codPais = codPais;
        this.nomSocio = nomSocio;
        this.apeSocio = apeSocio;
        this.codActEconomica = codActEconomica;
        this.codInstruccion = codInstruccion;
        this.nomJuridico = nomJuridico;
        this.stsSexo = stsSexo;
        this.fecNacimiento = fecNacimiento;
        this.stsCivil = stsCivil;
        this.stsSocio = stsSocio;
    }


    

    @Id

    @Column(name = "cod_socio", unique = true, nullable = false, precision = 10, scale = 0)
    public long getCodSocio() {
        return this.codSocio;
    }

    public void setCodSocio(long codSocio) {
        this.codSocio = codSocio;
    }

    @Column(name = "cod_tipo_socio", length = 1)
    public Character getCodTipoSocio() {
        return this.codTipoSocio;
    }

    public void setCodTipoSocio(Character codTipoSocio) {
        this.codTipoSocio = codTipoSocio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fec_ingreso", length = 13)
    public Date getFecIngreso() {
        return this.fecIngreso;
    }

    public void setFecIngreso(Date fecIngreso) {
        this.fecIngreso = fecIngreso;
    }

    @Column(name = "cod_tipo_persona", length = 1)
    public Character getCodTipoPersona() {
        return this.codTipoPersona;
    }

    public void setCodTipoPersona(Character codTipoPersona) {
        this.codTipoPersona = codTipoPersona;
    }

    @Column(name = "cod_tipo_id", length = 1)
    public Character getCodTipoId() {
        return this.codTipoId;
    }

    public void setCodTipoId(Character codTipoId) {
        this.codTipoId = codTipoId;
    }

    @Column(name = "num_id", length = 20)
    public String getNumId() {
        return this.numId;
    }

    public void setNumId(String numId) {
        this.numId = numId;
    }

    @Column(name = "cod_parroquia", precision = 6, scale = 0)
    public Integer getCodParroquia() {
        return this.codParroquia;
    }

    public void setCodParroquia(Integer codParroquia) {
        this.codParroquia = codParroquia;
    }

    @Column(name = "cod_canton", precision = 4, scale = 0)
    public Short getCodCanton() {
        return this.codCanton;
    }

    public void setCodCanton(Short codCanton) {
        this.codCanton = codCanton;
    }

    @Column(name = "cod_provincia", precision = 3, scale = 0)
    public Short getCodProvincia() {
        return this.codProvincia;
    }

    public void setCodProvincia(Short codProvincia) {
        this.codProvincia = codProvincia;
    }

    @Column(name = "cod_barrio", precision = 3, scale = 0)
    public Short getCodBarrio() {
        return codBarrio;
    }

    public void setCodBarrio(Short codBarrio) {
        this.codBarrio = codBarrio;
    }
    
    

    @Column(name = "cod_pais", precision = 3, scale = 0)
    public Short getCodPais() {
        return this.codPais;
    }

    public void setCodPais(Short codPais) {
        this.codPais = codPais;
    }

    @Column(name = "nom_socio", length = 100)
    public String getNomSocio() {
        return this.nomSocio;
    }

    public void setNomSocio(String nomSocio) {
        this.nomSocio = nomSocio;
    }

    @Column(name = "ape_socio", length = 100)
    public String getApeSocio() {
        return this.apeSocio;
    }

    public void setApeSocio(String apeSocio) {
        this.apeSocio = apeSocio;
    }

    @Column(name = "cod_act_economica", precision = 3, scale = 0)
    public Short getCodActEconomica() {
        return this.codActEconomica;
    }

    public void setCodActEconomica(Short codActEconomica) {
        this.codActEconomica = codActEconomica;
    }

    @Column(name = "cod_instruccion", precision = 3, scale = 0)
    public Short getCodInstruccion() {
        return this.codInstruccion;
    }

    public void setCodInstruccion(Short codInstruccion) {
        this.codInstruccion = codInstruccion;
    }

    @Column(name = "nom_juridico", length = 100)
    public String getNomJuridico() {
        return this.nomJuridico;
    }

    public void setNomJuridico(String nomJuridico) {
        this.nomJuridico = nomJuridico;
    }

    @Column(name = "sts_sexo", length = 1)
    public Character getStsSexo() {
        return this.stsSexo;
    }

    public void setStsSexo(Character stsSexo) {
        this.stsSexo = stsSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "fec_nacimiento", length = 13)
    public Date getFecNacimiento() {
        return this.fecNacimiento;
    }

    public void setFecNacimiento(Date fecNacimiento) {
        this.fecNacimiento = fecNacimiento;
    }

    @Column(name = "sts_civil", length = 1)
    public Character getStsCivil() {
        return this.stsCivil;
    }

    public void setStsCivil(Character stsCivil) {
        this.stsCivil = stsCivil;
    }

    @Column(name = "sts_socio", length = 1)
    public Character getStsSocio() {
        return this.stsSocio;
    }

    public void setStsSocio(Character stsSocio) {
        this.stsSocio = stsSocio;
    }

//    @Column(name = "nom_representante_legal", length = 100)
//    public String getNomRepresentanteLegal() {
//        return this.nomRepresentanteLegal;
//    }
//
//    public void setNomRepresentanteLegal(String nomRepresentanteLegal) {
//        this.nomRepresentanteLegal = nomRepresentanteLegal;
//    }
//
//    @Column(name = "ape_representante_legal", length = 100)
//    public String getApeRepresentanteLegal() {
//        return this.apeRepresentanteLegal;
//    }
//
//    public void setApeRepresentanteLegal(String apeRepresentanteLegal) {
//        this.apeRepresentanteLegal = apeRepresentanteLegal;
//    }
//
//    @Column(name = "cod_tipo_id_rep_legal", length = 1)
//    public Character getCodTipoIdRepLegal() {
//        return this.codTipoIdRepLegal;
//    }
//
//    public void setCodTipoIdRepLegal(Character codTipoIdRepLegal) {
//        this.codTipoIdRepLegal = codTipoIdRepLegal;
//    }
//
//    @Column(name = "num_id_rel_legal", length = 20)
//    public String getNumIdRelLegal() {
//        return this.numIdRelLegal;
//    }
//
//    public void setNumIdRelLegal(String numIdRelLegal) {
//        this.numIdRelLegal = numIdRelLegal;
//    }
//
//    @Column(name = "nom_conyuge", length = 100)
//    public String getNomConyuge() {
//        return this.nomConyuge;
//    }
//
//    public void setNomConyuge(String nomConyuge) {
//        this.nomConyuge = nomConyuge;
//    }
//
//    @Column(name = "ape_conyuge", length = 100)
//    public String getApeConyuge() {
//        return this.apeConyuge;
//    }
//
//    public void setApeConyuge(String apeConyuge) {
//        this.apeConyuge = apeConyuge;
//    }
//
//    @Temporal(TemporalType.DATE)
//    @Column(name = "fec_nac_con", length = 13)
//    public Date getFecNacCon() {
//        return this.fecNacCon;
//    }
//
//    public void setFecNacCon(Date fecNacCon) {
//        this.fecNacCon = fecNacCon;
//    }
//
//    @Column(name = "cod_tipo_id_con", length = 1)
//    public Character getCodTipoIdCon() {
//        return this.codTipoIdCon;
//    }
//
//    public void setCodTipoIdCon(Character codTipoIdCon) {
//        this.codTipoIdCon = codTipoIdCon;
//    }
//
//    @Column(name = "num_id_con", length = 20)
//    public String getNumIdCon() {
//        return this.numIdCon;
//    }
//
//    public void setNumIdCon(String numIdCon) {
//        this.numIdCon = numIdCon;
//    }
//
    @Column(name = "dir_dom", length = 100)
    public String getDirDom() {
        return this.dirDom;
    }

    public void setDirDom(String dirDom) {
        this.dirDom = dirDom;
    }
//
    @Column(name = "dir2_dom", length = 100)
    public String getDir2Dom() {
        return this.dir2Dom;
    }

    public void setDir2Dom(String dir2Dom) {
        this.dir2Dom = dir2Dom;
    }
//
    @Column(name = "tel_dom", length = 20)
    public String getTelDom() {
        return this.telDom;
    }

    public void setTelDom(String telDom) {
        this.telDom = telDom;
    }
//
    @Column(name = "tel_trabajo", length = 20)
    public String getTelTrabajo() {
        return this.telTrabajo;
    }

    public void setTelTrabajo(String telTrabajo) {
        this.telTrabajo = telTrabajo;
    }
//
    @Column(name = "tel_celular", length = 20)
    public String getTelCelular() {
        return this.telCelular;
    }

    public void setTelCelular(String telCelular) {
        this.telCelular = telCelular;
    }
//
//    @Column(name = "sts_operador_cel", length = 1)
//    public Character getStsOperadorCel() {
//        return this.stsOperadorCel;
//    }
//
//    public void setStsOperadorCel(Character stsOperadorCel) {
//        this.stsOperadorCel = stsOperadorCel;
//    }
//
    @Column(name = "dir_correo", length = 100)
    public String getDirCorreo() {
        return this.dirCorreo;
    }

    public void setDirCorreo(String dirCorreo) {
        this.dirCorreo = dirCorreo;
    }
//
//
//    public void setImgFoto(byte[] imgFoto) {
//        this.imgFoto = imgFoto;
//    }
//
//    @Column(name = "txt_link", length = 100)
//    public String getTxtLink() {
//        return this.txtLink;
//    }
//
//    public void setTxtLink(String txtLink) {
//        this.txtLink = txtLink;
//    }
//
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fec_usrmod", length = 29)
    public Date getFecUsrmod() {
        return this.fecUsrmod;
    }

    public void setFecUsrmod(Date fecUsrmod) {
        this.fecUsrmod = fecUsrmod;
    }
//
//    @Column(name = "cod_usrmod", precision = 12, scale = 0)
//    public Long getCodUsrmod() {
//        return this.codUsrmod;
//    }
//
//    public void setCodUsrmod(Long codUsrmod) {
//        this.codUsrmod = codUsrmod;
//    }
//
//    @Column(name = "nom_beneficiario", length = 100)
//    public String getNomBeneficiario() {
//        return this.nomBeneficiario;
//    }
//
//    public void setNomBeneficiario(String nomBeneficiario) {
//        this.nomBeneficiario = nomBeneficiario;
//    }
//
//    @Column(name = "ape_beneficiario", length = 100)
//    public String getApeBeneficiario() {
//        return this.apeBeneficiario;
//    }
//
//    public void setApeBeneficiario(String apeBeneficiario) {
//        this.apeBeneficiario = apeBeneficiario;
//    }
//
//    @Column(name = "cod_tipo_id_ben", length = 1)
//    public Character getCodTipoIdBen() {
//        return this.codTipoIdBen;
//    }
//
//    public void setCodTipoIdBen(Character codTipoIdBen) {
//        this.codTipoIdBen = codTipoIdBen;
//    }
//
//    @Column(name = "num_id_ben", length = 20)
//    public String getNumIdBen() {
//        return this.numIdBen;
//    }
//
//    public void setNumIdBen(String numIdBen) {
//        this.numIdBen = numIdBen;
//    }
//
    @Column(name = "dir_trabajo", length = 100)
    public String getDirTrabajo() {
        return this.dirTrabajo;
    }

    public void setDirTrabajo(String dirTrabajo) {
        this.dirTrabajo = dirTrabajo;
    }
//
//    @Column(name = "dir2_trabajo", length = 100)
//    public String getDir2Trabajo() {
//        return this.dir2Trabajo;
//    }
//
//    public void setDir2Trabajo(String dir2Trabajo) {
//        this.dir2Trabajo = dir2Trabajo;
//    }
//
//    @Column(name = "cod_tipo_sangre", length = 10)
//    public String getCodTipoSangre() {
//        return this.codTipoSangre;
//    }
//
//    public void setCodTipoSangre(String codTipoSangre) {
//        this.codTipoSangre = codTipoSangre;
//    }
//
    @Column(name = "val_ingreso_mensual", precision = 18)
    public BigDecimal getValIngresoMensual() {
        return this.valIngresoMensual;
    }

    public void setValIngresoMensual(BigDecimal valIngresoMensual) {
        this.valIngresoMensual = valIngresoMensual;
    }
//
//    @Temporal(TemporalType.DATE)
//    @Column(name = "fec_solicitud", length = 13)
//    public Date getFecSolicitud() {
//        return this.fecSolicitud;
//    }
//
//    public void setFecSolicitud(Date fecSolicitud) {
//        this.fecSolicitud = fecSolicitud;
//    }
//
//    @Column(name = "cod_origen_ingresos", length = 1)
//    public Character getCodOrigenIngresos() {
//        return this.codOrigenIngresos;
//    }
//
//    public void setCodOrigenIngresos(Character codOrigenIngresos) {
//        this.codOrigenIngresos = codOrigenIngresos;
//    }
//
    @Column(name = "val_activo", precision = 15)
    public BigDecimal getValActivo() {
        return this.valActivo;
    }

    public void setValActivo(BigDecimal valActivo) {
        this.valActivo = valActivo;
    }

    @Column(name = "val_pasivo", precision = 15)
    public BigDecimal getValPasivo() {
        return this.valPasivo;
    }

    public void setValPasivo(BigDecimal valPasivo) {
        this.valPasivo = valPasivo;
    }

    @Column(name = "val_patrimonio", precision = 15)
    public BigDecimal getValPatrimonio() {
        return this.valPatrimonio;
    }

    public void setValPatrimonio(BigDecimal valPatrimonio) {
        this.valPatrimonio = valPatrimonio;
    }

    @Column(name = "val_gastos_mensuales", precision = 15)
    public BigDecimal getValGastosMensuales() {
        return this.valGastosMensuales;
    }

    public void setValGastosMensuales(BigDecimal valGastosMensuales) {
        this.valGastosMensuales = valGastosMensuales;
    }
//
//    @Column(name = "cod_causal_vinculacion", length = 4)
//    public String getCodCausalVinculacion() {
//        return this.codCausalVinculacion;
//    }
//
//    public void setCodCausalVinculacion(String codCausalVinculacion) {
//        this.codCausalVinculacion = codCausalVinculacion;
//    }
//
//    @Temporal(TemporalType.DATE)
//    @Column(name = "fec_causal", length = 13)
//    public Date getFecCausal() {
//        return this.fecCausal;
//    }
//
//    public void setFecCausal(Date fecCausal) {
//        this.fecCausal = fecCausal;
//    }
//
//    @Column(name = "cod_tipo_vivienda", length = 1)
//    public Character getCodTipoVivienda() {
//        return this.codTipoVivienda;
//    }
//
//    public void setCodTipoVivienda(Character codTipoVivienda) {
//        this.codTipoVivienda = codTipoVivienda;
//    }
//
//    @Column(name = "val_vivienda", precision = 15)
//    public BigDecimal getValVivienda() {
//        return this.valVivienda;
//    }
//
//    public void setValVivienda(BigDecimal valVivienda) {
//        this.valVivienda = valVivienda;
//    }
//
//    @Column(name = "num_tiempo_trabajo", precision = 3, scale = 0)
//    public Short getNumTiempoTrabajo() {
//        return this.numTiempoTrabajo;
//    }
//
//    public void setNumTiempoTrabajo(Short numTiempoTrabajo) {
//        this.numTiempoTrabajo = numTiempoTrabajo;
//    }
//
//
//    public void setNumCargasFamiliares(Byte numCargasFamiliares) {
//        this.numCargasFamiliares = numCargasFamiliares;
//    }
//
    @Column(name = "cod_socio_conyuge", precision = 10, scale = 0)
    public Long getCodSocioConyuge() {
        return this.codSocioConyuge;
    }

    public void setCodSocioConyuge(Long codSocioConyuge) {
        this.codSocioConyuge = codSocioConyuge;
    }
//
//    @Column(name = "cod_socio_vinculado", precision = 10, scale = 0)
//    public Long getCodSocioVinculado() {
//        return this.codSocioVinculado;
//    }
//
//    public void setCodSocioVinculado(Long codSocioVinculado) {
//        this.codSocioVinculado = codSocioVinculado;
//    }
//
//
//    public void setCodRelacion(Byte codRelacion) {
//        this.codRelacion = codRelacion;
//    }
//
//    @Column(name = "txt_observacion_relacion", length = 50)
//    public String getTxtObservacionRelacion() {
//        return this.txtObservacionRelacion;
//    }
//
//    public void setTxtObservacionRelacion(String txtObservacionRelacion) {
//        this.txtObservacionRelacion = txtObservacionRelacion;
//    }
//
//
//    public void setCodOficina(Byte codOficina) {
//        this.codOficina = codOficina;
//    }
//
    @Column(name = "txt_lugar_trabajo", length = 100)
    public String getTxtLugarTrabajo() {
        return this.txtLugarTrabajo;
    }

    public void setTxtLugarTrabajo(String txtLugarTrabajo) {
        this.txtLugarTrabajo = txtLugarTrabajo;
    }
//
//    @Column(name = "cod_nivel_estudios", length = 1)
//    public Character getCodNivelEstudios() {
//        return this.codNivelEstudios;
//    }
//
//    public void setCodNivelEstudios(Character codNivelEstudios) {
//        this.codNivelEstudios = codNivelEstudios;
//    }
//
//    @Column(name = "sts_actualiza_web", length = 1)
//    public Character getStsActualizaWeb() {
//        return stsActualizaWeb;
//    }
//
//    public void setStsActualizaWeb(Character stsActualizaWeb) {
//        this.stsActualizaWeb = stsActualizaWeb;
//    }
    
    @Column(name = "cod_canton_nac", precision = 4, scale = 0)
    public long getCodCantonNac() {
        return codCantonNac;
    }

    public void setCodCantonNac(long codCantonNac) {
        this.codCantonNac = codCantonNac;
    }

    
//    @Override
//    public String toString() {
//        return "SgfSocio{" + "codSocio=" + codSocio + ", codTipoSocio=" + codTipoSocio + ", fecIngreso=" + fecIngreso + ", codTipoPersona=" + codTipoPersona + ", codTipoId=" + codTipoId + ", numId=" + numId + ", codParroquia=" + codParroquia + ", codCanton=" + codCanton + ", codProvincia=" + codProvincia + ", codPais=" + codPais + ", nomSocio=" + nomSocio + ", apeSocio=" + apeSocio + ", codActEconomica=" + codActEconomica + ", codInstruccion=" + codInstruccion + ", nomJuridico=" + nomJuridico + ", stsSexo=" + stsSexo + ", fecNacimiento=" + fecNacimiento + ", stsCivil=" + stsCivil + ", stsSocio=" + stsSocio + ", nomRepresentanteLegal=" + nomRepresentanteLegal + ", apeRepresentanteLegal=" + apeRepresentanteLegal + ", codTipoIdRepLegal=" + codTipoIdRepLegal + ", numIdRelLegal=" + numIdRelLegal + ", nomConyuge=" + nomConyuge + ", apeConyuge=" + apeConyuge + ", fecNacCon=" + fecNacCon + ", codTipoIdCon=" + codTipoIdCon + ", numIdCon=" + numIdCon + ", dirDom=" + dirDom + ", dir2Dom=" + dir2Dom + ", telDom=" + telDom + ", telTrabajo=" + telTrabajo + ", telCelular=" + telCelular + ", stsOperadorCel=" + stsOperadorCel + ", dirCorreo=" + dirCorreo + ", imgFoto=" + imgFoto + ", txtLink=" + txtLink + ", fecUsrmod=" + fecUsrmod + ", codUsrmod=" + codUsrmod + ", nomBeneficiario=" + nomBeneficiario + ", apeBeneficiario=" + apeBeneficiario + ", codTipoIdBen=" + codTipoIdBen + ", numIdBen=" + numIdBen + ", dirTrabajo=" + dirTrabajo + ", dir2Trabajo=" + dir2Trabajo + ", codTipoSangre=" + codTipoSangre + ", valIngresoMensual=" + valIngresoMensual + ", fecSolicitud=" + fecSolicitud + ", codOrigenIngresos=" + codOrigenIngresos + ", valActivo=" + valActivo + ", valPasivo=" + valPasivo + ", valPatrimonio=" + valPatrimonio + ", valGastosMensuales=" + valGastosMensuales + ", codCausalVinculacion=" + codCausalVinculacion + ", fecCausal=" + fecCausal + ", codTipoVivienda=" + codTipoVivienda + ", valVivienda=" + valVivienda + ", numTiempoTrabajo=" + numTiempoTrabajo + ", numCargasFamiliares=" + numCargasFamiliares + ", codSocioConyuge=" + codSocioConyuge + ", codSocioVinculado=" + codSocioVinculado + ", codRelacion=" + codRelacion + ", txtObservacionRelacion=" + txtObservacionRelacion + ", codOficina=" + codOficina + ", txtLugarTrabajo=" + txtLugarTrabajo + ", codNivelEstudios=" + codNivelEstudios + '}';
//    }




}
